{% set name = "cubedpandas" %}
{% set version = "0.2.37" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cubedpandas-{{ version }}.tar.gz
  sha256: 5f5cf789b43147e3bb5da1d98d35f154e8bc5752114a60ab7ce848dc42ff539a
  patches:
    - 0001-get-version.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  script_env:
    - VERSION={{ version }}

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - pandas
    - numpy
    - python-dateutil
    - datespan

test:
  imports:
    - cubedpandas
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Zeutschler/cubedpandas
  summary: CubedPandas offer a new easy, fast & fun approach to filter, navigate and analyze Pandas dataframes.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
